MODEL:
  TYPE: pjs
  NAME: pajigsaw_patch16_512
  DROP_PATH_RATE: 0.1
  NUM_CLASSES: 4
  PJS:
    EMBED_DIM: 384
    PATCH_SIZE: 16
    NUM_HEADS: 6
    DEPTH: 12
    C_DEPTH: 12
DATA:
  DATASET: pajigsaw
  IMG_SIZE: 512
